Fixed
Signed-off-by: Saint <arishabh748@gmail.com>
lexyclear/Discord3rdparties pull request #2
Opened 2022-04-19 10:54 UTC by saintwithataint

2022-04-19 15:25 UTC, taskylizard approved these changes

2022-04-20 01:45 UTC, lexyclear approved these changes
Approved

2022-04-20 01:46 UTC, lexyclear requested changes
hmm

2022-04-20 01:47 UTC, lexyclear commented
sure

2022-04-20 01:48 UTC, lexyclear approved these changes

2022-04-20 03:14 UTC, saintwithataint commented
why didn't you merge it

2022-04-20 08:11 UTC, merged